[versions]
kotlin = "2.3.0"
junit = "5.11.4"
kotlinx-serialization = "1.8.0"
plugin-publish = "2.1.1"
maven-publish = "0.34.0"
spotless = "7.0.2"
ktlint = "1.5.0"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-engine = { module = "org.junit.platform:junit-platform-engine" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-platform-reporting = { module = "org.junit.platform:junit-platform-reporting" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "plugin-publish" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
